### PR TITLE
fix: defer FK constraints when referenced tables don't exist yet

### LINKED ISSUE #155: Fix dependency handling: FK ordering, schema normalization, and function replacements
This patch fixes several bugs in pgschema's dependency handling:

## Issues Fixed

1. **FK-heavy tables could be reordered alphabetically during cycles**: When Kahn's algorithm encountered a cycle, it would fall back to alphabetical ordering, causing child tables to be created before parent tables. The fix breaks cycles deterministically based on source order and defers FK constraints until their referenced tables exist.

2. **Schema-qualified identifiers in strings weren't normalized**: When the desired schema was applied to a temporary schema, any schema-qualified identifiers inside strings (defaults, policy expressions, trigger bodies, etc.) were left untouched. The diff then emitted SQL that referenced the temp schema name instead of the real schema. The fix normalizes every textual field in the IR so the target schema name is restored everywhere.

3. **Function replacements always emitted DROP followed by CREATE**: If other objects referenced the function, the drop would fail before the replacement could run. The fix treats replacements as `CREATE OR REPLACE` operations only, and normalizes argument identities by stripping schema prefixes so `public.member_status` and `member_status` aren't treated as different signatures.

4. **Updated diff fixtures/tests**: Added coverage for deferred FK constraints, policy ordering, and normalized functions.

## Patch

I've attached a patch file with the complete fix. The patch is also available in this branch: https://github.com/pgschema/pgschema/compare/main...p-c-h-b:pgschema:fix/function-drops

Would you like me to open a PR, or would you prefer to review the patch first?

### PR DESCRIPTION
**Pull request by p-c-h-b**
This fixes a bug where FK-heavy tables could be reordered alphabetically whenever Kahn's algorithm encountered a cycle in the dependency graph. This caused child tables to be created before parent tables, leading to "relation does not exist" errors.

## Problem

When the topological sort encountered a cycle (e.g., two tables with mutual FK references), it would fall back to alphabetical sorting. This meant that tables like `adjustment` could be created before `review`, even though `adjustment` has a foreign key to `review`.

## Solution

1. **Deterministic cycle breaking**: Instead of falling back to alphabetical order, the algorithm now breaks cycles by selecting the next unprocessed table in the original insertion order.

2. **Deferred FK constraints**: FK constraints that reference tables that haven't been created yet are now deferred and added via `ALTER TABLE` after all tables exist.

## Changes

- Modified `topologicallySortTables()` and `topologicallySortViews()` to track insertion order and use it for deterministic cycle breaking
- Added `deferredConstraint` type to track FK constraints that need to be applied later
- Modified `generateCreateTablesSQL()` to return deferred policies and constraints
- Added `generateDeferredConstraintsSQL()` to apply FK constraints after all tables are created
- Added `shouldDeferConstraint()` helper to determine if an FK should be deferred
- Added test case `TestTopologicallySortTablesHandlesCycles()` covering cyclic dependencies

## Test Case

The new test verifies:
- Tables with linear dependencies are ordered correctly (a → b → c)
- Tables with cyclic dependencies are handled without errors (x ↔ y)
- Tables depending on cycles are still ordered after the cycle (z depends on y)
- Cycle members are ordered deterministically

Fixes #155 (partially - this is the first of three fixes mentioned in the issue)

### CODE REVIEW

**Review by p-c-h-b — COMMENTED** [review]
Both suggestions have been addressed in commit 5366345:
1. Added validation for empty constraint names in generateDeferredConstraintsSQL
2. Fixed the comment to accurately reflect insertion order instead of alphabetical order

**Review by tianzhou — CHANGES_REQUESTED** [review]

**Comment by tianzhou** [comment]
1. Let's also enhance the test case https://github.com/pgschema/pgschema/tree/main/testdata/diff/dependency/table_to_table to validate this fix.

1. pls remove xxx_actual.sql, xxx_expected.sql as those are test artifacts when the test fails.

**Comment by tianzhou** [comment]
@p-c-h-b have you forgot to push the update?

**Comment by p-c-h-b** [comment]
Rookie mistake! Should be good now.

File: testdata/dump/employee/pgschema.sql [hunk 1]
```diff
@@ -43,18 +43,6 @@ CREATE INDEX IF NOT EXISTS idx_audit_username ON audit (user_name);
 
 ALTER TABLE audit ENABLE ROW LEVEL SECURITY;
 
---
--- Name: audit_insert_system; Type: POLICY; Schema: -; Owner: -
```
Comment (tianzhou) [inline testdata/dump/employee/pgschema.sql]: The CRATE POLICY should be co-located with RLS in the above
